use_frameworks!

target 'MboxAppCommon_Example' do
  pod 'MboxAppCommon', :path => '../'

  target 'MboxAppCommon_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
